### ISSUE TITLE
Please Decrypt This Repository

### ISSUE THREAD

**Issue by BROTOKARMOKAR** [Datez-Kun/reverse-enginnering#1]
https://github.com/saydog/Virus-droid-creator

**Comment by Datez-Kun** [comment]
> https://github.com/saydog/Virus-droid-creator

This
https://github.com/Datez-Kun/reverse-enginnering/tree/master/Virus-droid-creator

**Comment by BROTOKARMOKAR** [comment]
@Datez-Kun can you teach me the decryption process of python ???

**Comment by Datez-Kun** [comment]
> @Datez-Kun can you teach me the decryption process of python ???
> 
> I mean How to Decompile This File ???
> https://github.com/saydog/Virus-droid-creator
> 
> please tell the manual @Datez-Kun

easy bro, just use your brain and make friends with google :)
